### ISSUE TITLE
Implement data caching

### ISSUE THREAD

**Issue by justin0022** [justin0022/dashboard#9]
Currently, every time a route gets loaded, all of the data gets refetched. Instead, the data should be cached and possibly prefetched (for instance, once home is loaded, start fetching the required data for `/student/`). 

Most likely this can be implemented using service workers.

**Comment by justin0022** [comment]
@soohyunkim could you look into the best way to implement this? I think it could be implemented within the `useData` hook.

**Comment by soohyunkim** [comment]
Closing the issue for now, though implementation could be improved
